//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.SampleForSuperset
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Car type.
    /// </summary>
    // *** Start programmer edit section *** (CarType CustomAttributes)

    // *** End programmer edit section *** (CarType CustomAttributes)
    public enum CarType
    {
        
        // *** Start programmer edit section *** (CarType.Coupe CustomAttributes)

        // *** End programmer edit section *** (CarType.Coupe CustomAttributes)
        Coupe,
        
        // *** Start programmer edit section *** (CarType.Sedan CustomAttributes)

        // *** End programmer edit section *** (CarType.Sedan CustomAttributes)
        Sedan,
        
        // *** Start programmer edit section *** (CarType.Crossover CustomAttributes)

        // *** End programmer edit section *** (CarType.Crossover CustomAttributes)
        Crossover,
    }
}
